C     INTERFACE SUBROUTINE FOR SOLVING A LINEAR SYSTEM WITH MA28 LIBRARY
C     WRITTEN BY YOUNGSUN HAN (2015.04.25)
      SUBROUTINE MA28_SOLVE_LINEAR_SYSTEM(N,NZ,A,LICN,ICN,LIRN,IRN,X,
     & ERROR)
C     THE PARAMETERS ARE AS FOLLOWS.....
C     N    :I: ORDER OF MATRIX (CONST)
C     NZ   :I: NUMBER OF NON-ZEROS IN INPUT MATRIX (CONST)
C     A    :D: DOUBLE ARRAY OF LENGTH LICN.
C              HOLDS NON-ZEROS OF MATRIX ON ENTIRY AND
C              NON-ZEROS OF FACTORS ON EXIT. (BY MA28)
C     LICN :I: LENGTH OF ARRAYS A AND ICN (CONST)
C     ICN  :I: INTEGER ARRAY OF LENGTH LICN.
C              HOLDS COLUMN INDICES ON ENTRY AND
C              COLUMN INDICES OF DECOMPOSED MATRIX ON EXIT. (BY MA28)
C     LIRN :I: LENGTH OF ARRAY IRN. (CONST)
C     IRN  :I: INTEGER ARRAY OF LENGTH LIRN.
C              HOLD ROW INDICES ON INPUT.
C              USED TO HOLD COLUMN ORIENTATION OF MATRIX. (BY MA28)
C     X    :D: DOUBLE ARRAY OF LENGTH N.
C              HOLDS RIGHT HAND SIDE AND
C              THE SOLUTION VECTOR ON EXIT. (BY MA28)
C     ERROR:I: INTEGER VARIABLE USED AS ERROR FLAG BY ROUTINE.
C              A POSITIVE OR ZERO VALUE ON EXIT INDICATES SUCCESS.
C              POOSIBLE NEGATIVE VALUES ARE -1 THROUGH -14.

      INTEGER N, NZ, LICN, LIRN, ERROR
      INTEGER IRN(LIRN), ICN(LICN)
      DOUBLE PRECISION A(LICN), X(N)

C     PRIVATE VARIABLES
C     IKEEP:I: INTEGER ARRAY OF LENGTH 5*N.
C              USED TO CONTAIN INFORMATION OF DECOMPOSITION BY MA28
C              SHOULD BE PRESERVED BY THE SUBSEQUENT CALLS
C              TO MA28B/BD OR MA28C/CD.
C     IW   :I: INTEGER ARRAY OF LENGTH 8*N (USED BY MA28)
C     W    :D: DOUBLE ARRAY OF LENGTH N (USED BY MA28)
C     U    :D: USED TO CONTROL BIAS FOR NUMERIC OR SPARSITY PIVOTING
C     MTYPE:I: USED TO TELL MA28 TO SOLVE THE DIRECT EQUATION
C              (MTYPE=1) OR ITS TRANSPOSE (MTYPE.NE.1).
      INTEGER IKEEP(N,5), IW(N,8), MTYPE
      DOUBLE PRECISION W(N), U

C     PARTIAL PIVOTING
      U=0.10D0

C     RESET THE ELEMENTS OF ARRAYS WITH 0
      IKEEP=0
      IW=0
      W=0

C     MA28AD SUBROUTINE CALL FOR DECOMPOSITION
      CALL MA28AD(N,NZ,A,LICN,IRN,LIRN,ICN,U,IKEEP,IW,W,ERROR)

      IF(ERROR.LT.0) THEN
        WRITE(*,100) ERROR
      END IF
100   FORMAT('ERROR OCCURS DURING DECOMPOSITION BY MA28AD:',I3)

C     TO SOLVE DIRECT EQUATION
      MTYPE=1

C     PRINT OUT X MATRIX
C      WRITE(*,*) 'INPUT B MATRIX:'
C      DO 200 I=1,N
C        WRITE(*,300) I, X(I)
C200   CONTINUE
C300   FORMAT(I6,':',E14.6)

C     MA28CD SUBROUTINE CALL FOR MATRIX PRODUCT
      CALL MA28CD(N,A,LICN,ICN,IKEEP,X,W,MTYPE)

C     PRINT OUT X MATRIX
C      WRITE(*,*) 'OUTPUT X MATRIX:'
C      DO 400 I=1,N
C        WRITE(*,300) I, X(I)
C400   CONTINUE

      END
