/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_kpfa_hadoop_PowerflowAnalysisJni */

#ifndef _Included_com_sun_kpfa_hadoop_PowerflowAnalysisJni
#define _Included_com_sun_kpfa_hadoop_PowerflowAnalysisJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_kpfa_hadoop_PowerflowAnalysisJni
 * Method:    PerformCtgAnalysis
 * Signature: (Lcom/sun/kpfa/hadoop/ContingencyData;[BLcom/sun/kpfa/hadoop/ResultDataMgmt;)Z
 */
JNIEXPORT jint JNICALL Java_com_sun_kpfa_hadoop_PowerflowAnalysisJni_PerformCtgAnalysis
  (JNIEnv *, jobject, jobject, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
